version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      # Use a different port to not collide with
      # locally installed postgres
      - '6432:5432'
  superadmin:
    image: superadmin
    build:
      dockerfile: ./apps/superadmin/Dockerfile
      context: ./
    # Uncomment to test build locally:
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:6432/${POSTGRES_DB}
    ports:
      - '3333:3333'
