version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      # Use a different port to not collide with
      # locally installed postgres
      - '6432:5432'
